const bridge = window.AndroidBridge || {};

export const useBridge = () => ({
  requestPermission: bridge.reqPerm || (() => Promise.resolve(false)),
  takePhoto: bridge.takePic || (() => Promise.resolve("")),
  getLocation: bridge.getLoc || (() => Promise.resolve("")),
  getDeviceInfo: bridge.getDev || (() => Promise.resolve("{}")),
  startSTT: bridge.stt || (() => Promise.resolve("")),
  pickFile: bridge.pickFile || (() => Promise.resolve("")),
  saveFile: bridge.saveFile || ((n, d) => Promise.resolve("")),
  readFile: bridge.readFile || ((p) => Promise.resolve("")),
  kvGet: bridge.kvGet || ((k) => Promise.resolve("")),
  kvSet: bridge.kvSet || ((k, v) => {}),
  kvDel: bridge.kvDel || ((k) => {}),
  getBattery: bridge.getBat || (() => Promise.resolve("-1")),
  getNetwork: bridge.getNet || (() => Promise.resolve("unknown")),
  getAppVersion: bridge.getVer || (() => Promise.resolve("unknown")),
  vibrate: bridge.vibrate || ((d) => {}),
  keepAwake: bridge.keepAwake || ((e) => {}),
  setClipboard: bridge.setClip || ((t) => {}),
  getClipboard: bridge.getClip || (() => Promise.resolve("")),
  syncNow: bridge.syncNow || (() => Promise.resolve("false")),
  speakText: bridge.speak || (() => {}),
  notify: bridge.notify || (() => {}),
  isAvailable: !!window.AndroidBridge,
  dbGet: bridge.dbGet || ((t, k) => Promise.resolve("")),
  dbSet: bridge.dbSet || ((t, k, v) => {}),
  dbDel: bridge.dbDel || ((t, k) => {}),
  dbClear: bridge.dbClear || ((t) => {}),
  syncEnq: bridge.syncEnq || ((a, t, k, v) => Promise.resolve("")),
  syncStat: bridge.syncStat || (() => Promise.resolve('{"pending":0,"failed":0}')),
});